### ISSUE TITLE
Hamstring damage per rage calculations 

### ISSUE THREAD

**Issue by Razorwynd** [TheGroxEmpire/TBC_DPS_Warrior_Sim#22]
It appears the hamstring damage per rage calculation is bugged and gives extremely high values...
![image](https://user-images.githubusercontent.com/26841661/120113235-2e5ed780-c13f-11eb-9799-e9b818a56c3a.png)

**Comment by TheGroxEmpire** [comment]
@Razorwynd I am not able to reproduce this behavior. Could you attach the config when this behavior appeared?

**Comment by Razorwynd** [comment]
After a bit of research, it turns this is largely a result of user error! It only occurs when you have the rotation set up to spam slam at a lower rage threshold (i.e., 50 rage) than the threshold assigned for hamstring (i.e., 70 rage) then you will get these weird results. I have attached an example config file
[hamstring-dmg-bug.txt](https://github.com/TheGroxEmpire/TBC_DPS_Warrior_Sim/files/6576430/hamstring-dmg-bug.txt)

![image](https://user-images.githubusercontent.com/26841661/120328381-60dc1200-c2b0-11eb-951d-0290f0521d32.png)

**Comment by TheGroxEmpire** [comment]
> After a bit of research, it turns this is largely a result of user error! It only occurs when you have the rotation set up to spam slam at a lower rage threshold (i.e., 50 rage) than the threshold assigned for hamstring (i.e., 70 rage). I have attached an example config file

Ah I see the problem, the statistics library that the sim uses simply doesn't work when the cast number is lower than 1. In one of my internal testing that I did long ago (Pre-Alpha stage), I tried calculating the DPR of Heroic strike as 2H that virtually never used Heroic strike due to rage limitation. The output was the same mess as this.
I fixed this by only showing HS DPR if the number of HS cast is greater than 1.0. I think I'll apply the same condition for other abilities DPR calculation. Currently they are showing the DPR value if cast number > 0.0.

> Nevertheless, it makes me wonder how the DPR calculations for weird abilities like Overpower/Hamstring/Slam/Heroic Strike are actually done. Hamstring appears to be also including extra damage from procs like flurry and lionheart champion, is that correct?

The abilities DPR are computed as following: ``((Normal DPS) - (DPS where ability X costs rage but has no effect)) / (rage cost of ability X)``. Basically it takes the normal DPS of your sim result and then subtracting it with the normal DPS of a sim with the ability not causing any effect (Damage, proc, etc) and then dividing it with the rage cost of the ability.

On the account of Hamstring, you'd be seeing more proc as you spam them, thus increasing the sim dps. The proc was intended to affect DPR computation. To speculate a bit, this probably was done to see how much DPR spamstring rotation would give in vanilla Classic. Though in TBC spamstring is no longer possible as windfury doesn't proc from yellows anymore. So it is a moot point without any other proc.

Overpower rage costs are computed as following: ``(Average rage lost from swaping stance) / (Average number of OP cast) + 5``.

And Heroic strike works as you explained it. It includes the rage lost from missing a mainhand white attack.

> I know Heroic strike includes the rage that is "lost" due to turning an otherwise white attack into a yellow attack. How about slam, does that include the cost of delaying a white attack by a variable amount?

Slam DPR currently doesn't include the cost of delaying white. However, since the sim is constant in doing its slam, it is possible to include the cost of delaying white into DPR calculation (I'll add this to TODO list).

**Comment by Razorwynd** [comment]
Wow, this is great! That is a pretty clever way to get at the DRP value of each ability... Interestingly, spamstring does still provide some value in with flurry and weapon procs.
> Slam DPR currently doesn't include the cost of delaying white. However, since the sim is constant in doing its slam, it is possible to include the cost of delaying white into DPR calculation (I'll add this to TODO list)<
Awesome, I would love to see an adjusted DRP on slam!
